/**
 * useMapData — V2: Loads province_data.json + diffuse/province_id PNGs.
 *
 * Returns everything the renderer needs:
 *  - provinceData (JSON with centroids, adjacency, terrain)
 *  - diffuse + provinceId images
 *  - provinceById lookup
 *  - loading / error state
 */

import { useState, useEffect, useRef } from 'react';
import type { MapData, ProvinceData } from '../../types';

const MAP_BASE = '/godonis/v2';

export interface MapAssets {
  provinceData: MapData;
  provinceById: Map<string, ProvinceData>;
  images: {
    diffuse: HTMLImageElement;
    provinceLookup: HTMLImageElement;
  };
}

export type MapLoadState =
  | { status: 'loading' }
  | { status: 'error'; error: string }
  | { status: 'ready'; assets: MapAssets };

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Failed to load image: ${src}`));
    img.src = src;
  });
}

export function useMapData(): MapLoadState {
  const [state, setState] = useState<MapLoadState>({ status: 'loading' });
  const loadedRef = useRef(false);

  useEffect(() => {
    if (loadedRef.current) return;
    loadedRef.current = true;

    async function load() {
      try {
        const [jsonRes, diffuse, provinceLookup] = await Promise.all([
          fetch(`${MAP_BASE}/province_data.json`).then(r => {
            if (!r.ok) throw new Error(`Failed to load province_data.json: ${r.status}`);
            return r.json() as Promise<MapData>;
          }),
          loadImage(`${MAP_BASE}/diffuse_map.png`),
          loadImage(`${MAP_BASE}/province_lookup.png`),
        ]);

        const provinceById = new Map<string, ProvinceData>();
        for (const p of jsonRes.provinces) {
          provinceById.set(p.id, p);
        }

        setState({
          status: 'ready',
          assets: {
            provinceData: jsonRes,
            provinceById,
            images: { diffuse, provinceLookup },
          },
        });
      } catch (err) {
        console.error('Map load error:', err);
        setState({ status: 'error', error: String(err) });
      }
    }

    load();
  }, []);

  return state;
}

/**
 * Build a pixel → provinceIndex lookup buffer from province_lookup.png.
 *
 * The lookup PNG is generated by process-map.ts and encodes the 1-based
 * province index directly in the R channel (+ G*256 for >255 provinces).
 * No color matching needed — each pixel already IS the province index.
 */
export function buildProvinceLookup(
  lookupImg: HTMLImageElement,
  _mapData: MapData
): Uint8Array {
  const canvas = document.createElement('canvas');
  canvas.width = lookupImg.width;
  canvas.height = lookupImg.height;
  const ctx = canvas.getContext('2d')!;
  ctx.drawImage(lookupImg, 0, 0);
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const { data } = imageData;

  const W = canvas.width;
  const H = canvas.height;
  const lookup = new Uint8Array(W * H);

  for (let i = 0; i < data.length; i += 4) {
    // R = low byte of province index, G = high byte (for >255 provinces)
    lookup[i / 4] = data[i] + data[i + 1] * 256;
  }

  return lookup;
}
